# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "6"
      platform: x86
    - nodejs_version: "8"
      platform: x86
    - nodejs_version: "9"
      platform: x86
    - nodejs_version: "10"
      platform: x86

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm i -g npm@^5
  - appveyor-retry yarn
  - appveyor-retry yarn global add bower
  - appveyor-retry yarn add mocha-appveyor-reporter # must be installed locally.
  - node --version
  - yarn --version


cache:
  - '%LOCALAPPDATA%\Yarn'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - git rev-parse HEAD
  - cmd: node_modules/.bin/ember try:each

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"



