# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm i -g npm@^5
  - appveyor-retry yarn
  - appveyor-retry yarn global add bower

cache:
  - '%LOCALAPPDATA%\Yarn'
  - '%APPDATA%\Roaming\bower'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - git rev-parse HEAD
  - node --version
  - npm --version
  - yarn --version
  - which yarn
  - yarn lint
  - yarn test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
